log:
  exp_name: napoleon-anything
guide:
  text: "A photo of Napoleon Bonaparte, {} view"
  diffusion_name: Linaqruf/anything-v3.0
  append_direction: True
  shape_path: shapes/napoleon.obj
optim:
  seed: 3
