guide:
  diffusion_name: v1-5-pruned-emaonly.safetensors
  reference_image_path: references/crocodile leather.png
  shape_path: ./shapes/ai/sofa_001.obj
  text: sofa, crocodile leather
  reference_image_repeat: 6
  upscale: True
  image_resolution: 512
log:
  exp_name: sofa_crocodile_reference
  exp_root: experiments
optim:
  seed: 3
